spring:
  application:
    name: billing
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  jackson:
    serialization.indent_output: true
    serialization.write_dates_as_timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:5432/dev-billing
    username: billing
    password: Qwerty321
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database: POSTGRESQL
    database-platform: kz.dits.billing.domain.util.FixedPostgreSQL82Dialect
    properties:
      hibernate.format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        concurrency: 4
        max-concurrency: 10
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

flyway:
  locations: classpath:/dev/db/migration
  clean-on-validation-error: true

server:
  port: 8090

application:
  rabbitmq:
    paymentEventQueue: billing-payment
